name: ✨ Feature Request
description: Suggest a new feature or enhancement for the documentation site
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see added to the documentation site.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: |
        A clear and concise description of what you want to happen.
        How would this feature work?
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New documentation section
        - Interactive component
        - Search improvement
        - Navigation enhancement
        - Visual/UI improvement
        - Performance improvement
        - Accessibility improvement
        - Mobile experience
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for usability
        - Critical - Essential feature
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this feature?
      options:
        - New users
        - Experienced traders
        - Developers
        - All users
        - Documentation contributors
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Do you have examples of this feature implemented elsewhere?
      placeholder: |
        Links to other documentation sites, mockups, or examples that demonstrate
        what you're looking for...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or details about the feature request.
      placeholder: Any additional information that would help us understand your request...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'd like to contribute to implementing this feature
        - label: I can provide design input or feedback
        - label: I can help with testing

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
