import React, { useEffect } from 'react';
import { useLocation } from '@docusaurus/router';

// Skip to content link for accessibility
function SkipToContent() {
  return (
    <a href="#__docusaurus_skipToContent_fallback" className="skip-to-content">
      Skip to main content
    </a>
  );
}

// Inject <link rel="alternate" type="text/markdown" href="<page>.md"> on every
// page so agents that discover a page via HTML know where to fetch the clean
// markdown version generated by @signalwire/docusaurus-plugin-llms-txt.
function MarkdownAlternateLink() {
  const location = useLocation();

  useEffect(() => {
    if (typeof document === 'undefined') return;

    const existing = document.querySelector(
      'link[rel="alternate"][type="text/markdown"]',
    );
    if (existing) existing.remove();

    const link = document.createElement('link');
    link.rel = 'alternate';
    link.type = 'text/markdown';
    link.href = location.pathname.replace(/\/$/, '') + '.md';
    document.head.appendChild(link);
  }, [location.pathname]);

  return null;
}

export default function Root({ children }) {
  return (
    <>
      <SkipToContent />
      <MarkdownAlternateLink />
      {children}
    </>
  );
}
